FROM postgres
ENV envType ${envType}


# docker build -t boozsoft-postgres:1.0 --build-arg envType=dev .
# docker run --restart=alaways --name boozsoft-postgres -v /boozdata/pods -e POSTGRES_PASSWORD=Sigoo@@123 -d -p 5432:5432 postgres